server:
  port: 8080 # Backend service startup port

spring:
  application:
    name: LingoFlowBackend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # connect lingo_db database
    url: jdbc:mysql://localhost:3306/lingo_db?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456

mybatis-plus:
  global-config:
    db-config:
      table-prefix: lingo_ # Automatic mapping table prefix
      id-type: auto # Auto-incrementing primary key
  configuration:
    map-underscore-to-camel-case: true # Enable camelCase naming conversion
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # Print SQL statements